/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitingApprovalRouteImport } from './routes/waiting-approval'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PProductIdRouteImport } from './routes/p.$productId'
import { Route as DashboardTransactionsRouteImport } from './routes/_dashboard/transactions'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardRecoveryRouteImport } from './routes/_dashboard/recovery'
import { Route as DashboardProductsRouteImport } from './routes/_dashboard/products'
import { Route as DashboardPixelRouteImport } from './routes/_dashboard/pixel'
import { Route as DashboardPaymentSummaryRouteImport } from './routes/_dashboard/payment-summary'
import { Route as DashboardFilesRouteImport } from './routes/_dashboard/files'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as ApiPublicPaymentWebhookRouteImport } from './routes/api/public/payment-webhook'
import { Route as DashboardReportsTrafficRouteImport } from './routes/_dashboard.reports.traffic'
import { Route as ApiPublicHooksReconcilePendingPaymentsRouteImport } from './routes/api/public/hooks/reconcile-pending-payments'
import { Route as ApiPublicHooksProcessWebhookQueueRouteImport } from './routes/api/public/hooks/process-webhook-queue'
import { Route as ApiPublicHooksDailyPaymentSummaryRouteImport } from './routes/api/public/hooks/daily-payment-summary'

const WaitingApprovalRoute = WaitingApprovalRouteImport.update({
  id: '/waiting-approval',
  path: '/waiting-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProductIdRoute = PProductIdRouteImport.update({
  id: '/p/$productId',
  path: '/p/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecoveryRoute = DashboardRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPixelRoute = DashboardPixelRouteImport.update({
  id: '/pixel',
  path: '/pixel',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentSummaryRoute = DashboardPaymentSummaryRouteImport.update({
  id: '/payment-summary',
  path: '/payment-summary',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFilesRoute = DashboardFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicPaymentWebhookRoute = ApiPublicPaymentWebhookRouteImport.update({
  id: '/api/public/payment-webhook',
  path: '/api/public/payment-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsTrafficRoute = DashboardReportsTrafficRouteImport.update({
  id: '/reports/traffic',
  path: '/reports/traffic',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicHooksReconcilePendingPaymentsRoute =
  ApiPublicHooksReconcilePendingPaymentsRouteImport.update({
    id: '/api/public/hooks/reconcile-pending-payments',
    path: '/api/public/hooks/reconcile-pending-payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessWebhookQueueRoute =
  ApiPublicHooksProcessWebhookQueueRouteImport.update({
    id: '/api/public/hooks/process-webhook-queue',
    path: '/api/public/hooks/process-webhook-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyPaymentSummaryRoute =
  ApiPublicHooksDailyPaymentSummaryRouteImport.update({
    id: '/api/public/hooks/daily-payment-summary',
    path: '/api/public/hooks/daily-payment-summary',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/waiting-approval': typeof WaitingApprovalRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/files': typeof DashboardFilesRoute
  '/payment-summary': typeof DashboardPaymentSummaryRoute
  '/pixel': typeof DashboardPixelRoute
  '/products': typeof DashboardProductsRoute
  '/recovery': typeof DashboardRecoveryRoute
  '/settings': typeof DashboardSettingsRoute
  '/transactions': typeof DashboardTransactionsRoute
  '/p/$productId': typeof PProductIdRoute
  '/reports/traffic': typeof DashboardReportsTrafficRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
  '/api/public/hooks/daily-payment-summary': typeof ApiPublicHooksDailyPaymentSummaryRoute
  '/api/public/hooks/process-webhook-queue': typeof ApiPublicHooksProcessWebhookQueueRoute
  '/api/public/hooks/reconcile-pending-payments': typeof ApiPublicHooksReconcilePendingPaymentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/waiting-approval': typeof WaitingApprovalRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/files': typeof DashboardFilesRoute
  '/payment-summary': typeof DashboardPaymentSummaryRoute
  '/pixel': typeof DashboardPixelRoute
  '/products': typeof DashboardProductsRoute
  '/recovery': typeof DashboardRecoveryRoute
  '/settings': typeof DashboardSettingsRoute
  '/transactions': typeof DashboardTransactionsRoute
  '/p/$productId': typeof PProductIdRoute
  '/reports/traffic': typeof DashboardReportsTrafficRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
  '/api/public/hooks/daily-payment-summary': typeof ApiPublicHooksDailyPaymentSummaryRoute
  '/api/public/hooks/process-webhook-queue': typeof ApiPublicHooksProcessWebhookQueueRoute
  '/api/public/hooks/reconcile-pending-payments': typeof ApiPublicHooksReconcilePendingPaymentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/waiting-approval': typeof WaitingApprovalRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/files': typeof DashboardFilesRoute
  '/_dashboard/payment-summary': typeof DashboardPaymentSummaryRoute
  '/_dashboard/pixel': typeof DashboardPixelRoute
  '/_dashboard/products': typeof DashboardProductsRoute
  '/_dashboard/recovery': typeof DashboardRecoveryRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/transactions': typeof DashboardTransactionsRoute
  '/p/$productId': typeof PProductIdRoute
  '/_dashboard/reports/traffic': typeof DashboardReportsTrafficRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
  '/api/public/hooks/daily-payment-summary': typeof ApiPublicHooksDailyPaymentSummaryRoute
  '/api/public/hooks/process-webhook-queue': typeof ApiPublicHooksProcessWebhookQueueRoute
  '/api/public/hooks/reconcile-pending-payments': typeof ApiPublicHooksReconcilePendingPaymentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/blocked'
    | '/waiting-approval'
    | '/dashboard'
    | '/files'
    | '/payment-summary'
    | '/pixel'
    | '/products'
    | '/recovery'
    | '/settings'
    | '/transactions'
    | '/p/$productId'
    | '/reports/traffic'
    | '/api/public/payment-webhook'
    | '/api/public/hooks/daily-payment-summary'
    | '/api/public/hooks/process-webhook-queue'
    | '/api/public/hooks/reconcile-pending-payments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/blocked'
    | '/waiting-approval'
    | '/dashboard'
    | '/files'
    | '/payment-summary'
    | '/pixel'
    | '/products'
    | '/recovery'
    | '/settings'
    | '/transactions'
    | '/p/$productId'
    | '/reports/traffic'
    | '/api/public/payment-webhook'
    | '/api/public/hooks/daily-payment-summary'
    | '/api/public/hooks/process-webhook-queue'
    | '/api/public/hooks/reconcile-pending-payments'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/admin'
    | '/auth'
    | '/blocked'
    | '/waiting-approval'
    | '/_dashboard/dashboard'
    | '/_dashboard/files'
    | '/_dashboard/payment-summary'
    | '/_dashboard/pixel'
    | '/_dashboard/products'
    | '/_dashboard/recovery'
    | '/_dashboard/settings'
    | '/_dashboard/transactions'
    | '/p/$productId'
    | '/_dashboard/reports/traffic'
    | '/api/public/payment-webhook'
    | '/api/public/hooks/daily-payment-summary'
    | '/api/public/hooks/process-webhook-queue'
    | '/api/public/hooks/reconcile-pending-payments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BlockedRoute: typeof BlockedRoute
  WaitingApprovalRoute: typeof WaitingApprovalRoute
  PProductIdRoute: typeof PProductIdRoute
  ApiPublicPaymentWebhookRoute: typeof ApiPublicPaymentWebhookRoute
  ApiPublicHooksDailyPaymentSummaryRoute: typeof ApiPublicHooksDailyPaymentSummaryRoute
  ApiPublicHooksProcessWebhookQueueRoute: typeof ApiPublicHooksProcessWebhookQueueRoute
  ApiPublicHooksReconcilePendingPaymentsRoute: typeof ApiPublicHooksReconcilePendingPaymentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiting-approval': {
      id: '/waiting-approval'
      path: '/waiting-approval'
      fullPath: '/waiting-approval'
      preLoaderRoute: typeof WaitingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$productId': {
      id: '/p/$productId'
      path: '/p/$productId'
      fullPath: '/p/$productId'
      preLoaderRoute: typeof PProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/transactions': {
      id: '/_dashboard/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/recovery': {
      id: '/_dashboard/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof DashboardRecoveryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/products': {
      id: '/_dashboard/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pixel': {
      id: '/_dashboard/pixel'
      path: '/pixel'
      fullPath: '/pixel'
      preLoaderRoute: typeof DashboardPixelRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/payment-summary': {
      id: '/_dashboard/payment-summary'
      path: '/payment-summary'
      fullPath: '/payment-summary'
      preLoaderRoute: typeof DashboardPaymentSummaryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/files': {
      id: '/_dashboard/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof DashboardFilesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/payment-webhook': {
      id: '/api/public/payment-webhook'
      path: '/api/public/payment-webhook'
      fullPath: '/api/public/payment-webhook'
      preLoaderRoute: typeof ApiPublicPaymentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/reports/traffic': {
      id: '/_dashboard/reports/traffic'
      path: '/reports/traffic'
      fullPath: '/reports/traffic'
      preLoaderRoute: typeof DashboardReportsTrafficRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/hooks/reconcile-pending-payments': {
      id: '/api/public/hooks/reconcile-pending-payments'
      path: '/api/public/hooks/reconcile-pending-payments'
      fullPath: '/api/public/hooks/reconcile-pending-payments'
      preLoaderRoute: typeof ApiPublicHooksReconcilePendingPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-webhook-queue': {
      id: '/api/public/hooks/process-webhook-queue'
      path: '/api/public/hooks/process-webhook-queue'
      fullPath: '/api/public/hooks/process-webhook-queue'
      preLoaderRoute: typeof ApiPublicHooksProcessWebhookQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-payment-summary': {
      id: '/api/public/hooks/daily-payment-summary'
      path: '/api/public/hooks/daily-payment-summary'
      fullPath: '/api/public/hooks/daily-payment-summary'
      preLoaderRoute: typeof ApiPublicHooksDailyPaymentSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardFilesRoute: typeof DashboardFilesRoute
  DashboardPaymentSummaryRoute: typeof DashboardPaymentSummaryRoute
  DashboardPixelRoute: typeof DashboardPixelRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardRecoveryRoute: typeof DashboardRecoveryRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardReportsTrafficRoute: typeof DashboardReportsTrafficRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardFilesRoute: DashboardFilesRoute,
  DashboardPaymentSummaryRoute: DashboardPaymentSummaryRoute,
  DashboardPixelRoute: DashboardPixelRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardRecoveryRoute: DashboardRecoveryRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardReportsTrafficRoute: DashboardReportsTrafficRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BlockedRoute: BlockedRoute,
  WaitingApprovalRoute: WaitingApprovalRoute,
  PProductIdRoute: PProductIdRoute,
  ApiPublicPaymentWebhookRoute: ApiPublicPaymentWebhookRoute,
  ApiPublicHooksDailyPaymentSummaryRoute:
    ApiPublicHooksDailyPaymentSummaryRoute,
  ApiPublicHooksProcessWebhookQueueRoute:
    ApiPublicHooksProcessWebhookQueueRoute,
  ApiPublicHooksReconcilePendingPaymentsRoute:
    ApiPublicHooksReconcilePendingPaymentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
